### PR TITLE
Add Intel oneAPI Toolkits build support.

### PR DESCRIPTION
**Pull request by CZHU20**
New CMake system has been tested with GNU / Intel compilers and with/without Trilinos.

### CODE REVIEW

**Comment by CZHU20** [comment]
I have a couple questions:
1. I couldn't understand svFSI/Code/CMake/FindINTELRUNTIME.cmake, so I left `SV_USE_INTEL` to be `OFF`. This does not affect the current Intel build. Can FindINTELRUNTIME.cmake be safely removed?

2. The opensource license in README file is inconsistent. In the introduction, it's MIT License, while at the bottom, we said it's BSD 3-Clause. We need to decide on one.

**Comment by CZHU20** [comment]
TODO: remove license information from README and keep the one on GitHub system.

**Comment by vvedula22** [comment]
@CZHU20 Is your TODO list done and included in this pull request?

**Comment by CZHU20** [comment]
@vvedula22 Yes. I just updated the README.

**Comment by vvedula22** [comment]
@CZHU20 are the changes in ALLFUN.f required for this pull request? If not, perhaps it is better to update all the IF-ELSE conditions in a separate commit and let this one be for oneAPI alone?

**Comment by CZHU20** [comment]
@vvedula22 Yes, the change in ALLFUN.F is required for Intel. If left out, there will be some inexplicable errors...

**Comment by vvedula22** [comment]
Ah! didn't show up in my test though. Merging anyway.

**Pull request merged**
